name: apoyo_emocional_ia_app
description: Proyecto de IA para apoyo emocional con Gemini, Firebase y Flutter.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  #  MÓDULOS DE FIREBASE Y BACKEND
  firebase_core: ^2.27.0 
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.17.0
  url_launcher: ^6.2.5
  #  MÓDULOS DE INTELIGENCIA ARTIFICIAL Y VOZ (TTS)
  google_generative_ai: ^0.4.7
  flutter_tts: ^4.1.0    # Texto a Voz (TTS) - La IA te hablará
  
  #  MÓDULOS DE DISEÑO AVANZADO (TASKER UI / ANIMACIÓN)
  lottie: ^3.1.2 
  flutter_staggered_grid_view: ^0.7.0 
  animate_do: ^3.0.2 
  google_mlkit_face_detection: ^0.10.0
  #  UTILIDADES
  webview_flutter: ^4.8.0 
  webview_flutter_android: ^3.11.0
  webview_flutter_wkwebview: ^3.9.0
  intl: ^0.19.0 
  path_provider: ^2.1.3 
  cupertino_icons: ^1.0.8 
  camera: ^0.10.5
  # camera, tflite_flutter, speech_to_text eliminados para estabilidad.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/